LookUpGroup27/LookUp

app/src/main/java/com/github/lookupgroup27/lookup/ui/authentication/SignIn.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/map/Map.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Calendar.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Landing.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Menu.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Quiz.kt

This PR introduces the foundational structure for the project. It sets up the necessary configurations and directory structure required for future development.

chore: add initial project skeleton

---

app/build.gradle.kts
app/src/androidTest/java/com/github/lookupgroup27/lookup/screen/CalendarScreenTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/CalendarViewModel.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Calendar.kt
gradle/libs.versions.toml

This pull request introduces the implementation of the **Calendar Screen** feature with dynamic event handling, multi-day and recurring event support, as well as UI tests. The PR also includes necessary dependency updates in the build files.
- **Calendar Screen:**
- Display a calendar view with selectable dates.
- Show events for the selected day and handle multi-day events correctly.
- Search functionality to filter and display events by name.
- Navigate between months with smooth transitions.
- **Event Handling:**
- Support for both recurring and multi-day events.
- Events are displayed in a list for the selected day, with details like title and date.
- **UI Tests:**
- Tests for verifying the correct display of months, navigation buttons, and day selection.
- Search button and lookup …

feat: Implement Calendar Screen with event handling, tests, and updated dependencies

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/authentication/SignInKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/map/MapKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/CalendarKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/LandingKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/MenuKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/QuizKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/profile/ProfileKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/skytracker/SkyTrackerKtTest.kt

This PR addresses the following changes to improve the structure and naming consistency of test files:
1. **Renamed Test Files and Classes**:
- Renamed several test files and their corresponding classes to ensure they follow proper naming conventions and are correctly linked in Android Studio.
- This helps in better test discovery and avoids potential issues with mismatches between file names and class names.
2. **Moved `MapKtTest.kt` to the Correct Package**:
- The `MapKtTest.kt` file was located in the wrong package. It has been moved to its correct package to match the structure of the source code and ensure tests run properly in the correct context.
- **File Renames**:
- `LoginTest.kt` → `SignInKtTest.kt`
- `MapScreenTest.kt` → `MapKtTest.kt`
- `CalendarScreenTest.kt` → …

Rename Test Files and Classes, and Move `MapKtTest.kt` to Correct Package

---

app/build.gradle.kts
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/calendar/CalendarKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/CalendarScreenTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/MainActivity.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/CalendarViewModel.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/HttpIcalRepository.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/IcalRepository.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/MockIcalRepository.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/calendar/Calendar.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Calendar.kt
app/src/main/java/com/github/lookupgroup27/lookup/util/DateUtils.kt
app/src/test/java/com/github/lookupgroup27/lookup/ui/model/calendar/CalendarViewModelTest.kt
gradle/libs.versions.toml

This PR implements various optimizations and new features for the calendar functionality in the application. The key changes are as follows:
- **IcalRepository Integration**: Introduced `IcalRepository` interface and implemented `HttpIcalRepository` and `MockIcalRepository` classes to handle calendar data fetching. This allows for better testing and flexibility in data retrieval methods.
- **CalendarViewModel Refactor**: Updated `CalendarViewModel` to use the repository pattern for fetching iCal data. This includes:
- Replacing the use of `OkHttpClient` within the ViewModel with `IcalRepository`.
- Creating a companion object with a `ViewModelProvider.Factory` for easier instantiation.
- Switched from using `mutableStateListOf<VEvent>()` to `MutableStateFlow<List<VEvent>>`. This ensures …

feat: Calendar Optimization and IcalRepository Integration

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/calendar/HttpIcalRepositoryTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/calendar/HttpIcalRepository.kt

This PR introduces unit tests for `HttpIcalRepository`, ensuring robust handling of various network conditions.
- **New CustomResponseInterceptor**: Mocks network responses, enabling tests without actual network requests.
- **Test Scenarios**:
- Successful response with mock iCal data
- Error response to validate null handling
- Empty response body to ensure correct null return
- Simulated network failure to verify exception handling
- These tests improve repository reliability by verifying behavior under different network conditions.
This setup ensures `HttpIcalRepository` behaves as expected, regardless of network reliability.

test: Add Unit Tests for HttpIcalRepository 

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/profile/ProfileInformationKtTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/profile/ProfileRepository.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/profile/ProfileRepositoryFirestore.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/profile/ProfileViewModel.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/profile/ProfileInformation.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/profile/ProfileRepositoryFirestoreTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/profile/ProfileViewModelTest.kt

This pull request introduces the functionality to delete a user’s profile from Firestore. The new `deleteUserProfile` method in `ProfileRepositoryFirestore` enables this capability, allowing authenticated users to remove their stored profile data.
**Changes :**
- Added `deleteUserProfile` method to `ProfileRepositoryFirestore`.
- Updated test suite with:
- Success scenario for profile deletion.
- Failure scenario where deletion encounters an error.
- Verification that deletion does not proceed if no user is logged in.
**Related Issues :**
Closes issue #85

feature: delete profile

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/feed/FeedScreenTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/map/MapKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/MenuKtTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/navigation/NavigationActions.kt

**Issue**: This PR addresses the issue where the app screen briefly flickers when a user clicks the navigation button for the currently active screen, as described in https://github.com/LookUpGroup27/LookUp/issues/103.
---
This PR resolves the flickering effect observed when clicking the navigation bar button for an already active screen. This fix enhances user experience by removing unnecessary visual distractions and ensuring stable navigation behavior.
---
- Added a check that you don't ask to navigate to the current screen in `BottomNavigationMenu.kt`
---
- Manually tested to confirm the flickering issue is resolved when clicking the active screen’s button.
- Verified that other navigation bar buttons function as expected without any flicker or unintended effects.

Fixes Flickering Effect on Active Screen Navigation Button

---

app/src/main/java/com/github/lookupgroup27/lookup/model/post/PostsRepositoryFirestore.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/post/PostsRepositoryFirestoreTest.kt

- Updated "likes" field to safely cast from Long to Int
- Updated "latitude" and "longitude" fields to safely cast from Long to Double
- Ensures compatibility with Firebase data types, preventing runtime casting errors
- Adjusted tests to reflect these changes, ensuring mocked data uses safe casting to prevent runtime errors with Firestore data types
Closes issue #114

fix: cast safely fields in getPosts method

---

app/src/main/java/com/github/lookupgroup27/lookup/ui/profile/Profile.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/profile/components/ProfileButtons.kt

**Description:** This PR refactors the ProfileButton composable by moving it to its own file to improve code readability and maintainability.
**Changes Made:**
Created a new file for the ProfileButton composable.
Organized the file under ui/profile/components/ to align with best practices for organizing sub-composables used across the same screen.
Rationale: Separating ProfileButton into its own file allows for a modular component structure and facilitates future reusability without cluttering the main screen file.
Linked Issue: Closes #128

Refactor ProfileButton to a Separate Composable File

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/authentication/SignInKtTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/authentication/SignIn.kt

This PR addresses the misalignment issue of the "Go Back" button on the Sign-In screen. The button is now correctly positioned in the top-left corner. A regression test has been added to verify that the button remains in the correct position in future updates.
- Implemented a regression test to check that the "Go Back" button remains in the top-left corner of the screen.

Fix Go Back Button Position on Sign-In Screen and Add Regression Test

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/googlemap/GoogleMapKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/image/ImagePreviewDialogTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/image/ImageReviewKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/image/TakeImageKtTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/MainActivity.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/location/LocationProviderSingleton.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/post/PostsRepositoryFirestore.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/googlemap/GoogleMap.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/googlemap/components/AddMapMarker.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/googlemap/components/MapControls.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/googlemap/components/MapView.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/ImagePreviewDialog.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/ImageReview.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/TakeImage.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/post/PostsViewModel.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/theme/Color.kt

This pull request implements the feature to allow users to take pictures and add markers on the map at the location where the picture was taken. The following changes have been made:
- Added Picture Markers on Google Map: Users can now add markers on the map to indicate where they captured a picture. When clicking a marker, an image preview dialog opens to display the picture along with the username of the person who posted it.
- Floating Action Button for Capturing Images: Added a FAB button on the map screen to allow users to take pictures directly. (when the user is not logged in, the FAB leads to the sign in screen)
- Current User Location as Blue Dot: The user's current location is now represented as the standard blue dot on the Google map instead of a marker.
- Image Review Updates: …

feat: add picture markers on map

---

app/src/main/java/com/github/lookupgroup27/lookup/ui/feed/Feed.kt

This PR introduces a Toast notification in the FeedScreen to enhance user feedback. When an unauthenticated user (with an empty userEmail) attempts to rate a photo, a Toast message is displayed prompting them to sign in.
**Changes:**
- Added a Toast notification in the FeedScreen that informs users to sign in when trying to rate photos without being authenticated.
**Reason:**
This change improves the user experience by providing immediate feedback when users perform actions that require authentication. It ensures users understand the need to sign in to access certain features.
**Related Issues:**
Closes Issue #149

Add sign-in check for photo rating in feed

---

app/src/main/java/com/github/lookupgroup27/lookup/ui/googlemap/components/MapControls.kt

Modified the MapControls Composable to correctly indicate if the Auto Centering buttons have been clicked on in the Google Map screen.

fix: correctly highlight buttons in Google Map screen

---

app/src/main/java/com/github/lookupgroup27/lookup/ui/image/ImageReview.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/ImageViewModel.kt
app/src/test/java/com/github/lookupgroup27/lookup/ui/image/ImageViewModelTest.kt
gradle/wrapper/gradle-wrapper.properties

This pull request refactors the codebase by reorganizing files related to the `ImageViewModel` and its associated tests. Specifically:
- **Renamed and moved**:
- `ImageViewModel.kt` from the `model/image` package to the `ui/image` package.
- `ImageViewModelTest.kt` from the `model/image` package to the `ui/image` package.
- Updated package declarations to reflect the new location of the files.
> [!IMPORTANT]
This pull request also address an update to the gradle wrapper version. This will make sure the project is up to date with the latest version of gradle.

Fix ImageViewModel package

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/image/ImageReviewKtTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/MainActivity.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/feed/ProximityFetcher.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/post/Post.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/post/PostsRepositoryFirestore.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/feed/Feed.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/ImageReview.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/image/TakeImage.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/navigation/NavigationActions.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/profile/Collection.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/feed/ProximityAndTimePostFetcherTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/post/PostsRepositoryFirestoreTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/ui/navigation/NavigationActionsTest.kt

This pull request updates the feed to make it time-sensitive, ensuring that more recent posts appear higher in the feed while maintaining proximity-based sorting.
- Added a timestamp field to the `Post` class, with a default value of 0L to ensure backward compatibility.
- Updated the `ProximityPostFetcher` to sort posts not only by proximity but also by recency, with more recent posts appearing higher in the feed.
- Modified the getPosts method in `PostsRepositoryFirestore` to handle the timestamp field when retrieving posts from Firestore.
Note: The code coverage for this PR is lower than expected because some lines of pre-existing code are not covered. These lines were not introduced or modified as part of this PR and include areas like the collection screen, parts of the …

feat: make feed time sensitive

---

app/src/main/java/com/github/lookupgroup27/lookup/model/map/renderables/Star.kt

Stars were becoming distorted (appearing as ellipses) when rotating the camera along different axes, affecting the visual quality of the sky rendering.
- Modified the billboard matrix calculation to properly extract camera orientation from the view matrix
- Corrected the order of matrix transformations to maintain circular shape
- Simplified vector calculations to improve numerical stability
- Used view matrix columns directly for billboard orientation
- Verified stars maintain circular shape during camera rotation on all axes
- Tested with different star sizes and positions
- Confirmed proper rendering at extreme viewing angles
Closes #231

Fix star shape distortion during camera rotation

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/SampleScreenTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/profile/ChangeAvatarButtonTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/map/Camera.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/map/CameraTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/map/renderables/utils/BufferUtilsTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/map/renderables/utils/GeometryUtilsTest.kt
app/src/test/java/com/github/lookupgroup27/lookup/model/map/stars/StarsLoaderTest.kt

This pull request introduces several new unit and UI tests to improve the app's overall line coverage:
**Composable Tests:**
- Added tests for `ChangeAvatarButton` to verify its conditional rendering and interaction logic based on avatar selection status.
- Added tests for `SampleScreen` to validate text display, back button functionality, and UI element presence using test tags.
**Utility Tests:**
- Wrote tests for the `generateCircularGeometry` method in `GeometryUtils`, ensuring correct vertex and index generation for circular shapes in OpenGL rendering.
- Added a test for the `ShortArray.toBuffer()` extension method in `BufferUtils`, verifying proper conversion of arrays to OpenGL-compatible buffers.
**Class-Specific Tests:**
- Added tests for the `StarsLoader` class to verify correct …

test: improve general code coverage

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/planetselection/PlanetSelectionScreenTest.kt
app/src/main/java/com/github/lookupgroup27/lookup/model/planetselection/PlanetSurfaceView.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/planetselection/PlanetSelectionScreen.kt

This pull request refactors the `PlanetSelectionScreen` to address layout issues encountered on physical devices. The modifications ensure all components are displayed correctly and are no longer obscured by the `GLSurfaceView`. Additionally, a clear separation between UI elements and OpenGL rendering was introduced.
**Replaced Surface with Scaffold**:
- Migrated the `PlanetSelectionScreen` to use Scaffold for separation of the top bar (UI components) and the content (OpenGL rendering).
**PlanetSurfaceView**: 
- Enabled transparency
This PR is related to PR #298

fix: Planet Selection Screen not rendering correctly on real phone

---

app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/map/MapKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/LandingKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/ui/overview/MenuKtTest.kt
app/src/androidTest/java/com/github/lookupgroup27/lookup/utils/TestNetworkuUtils.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/navigation/BottomNavigationMenu.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Landing.kt
app/src/main/java/com/github/lookupgroup27/lookup/ui/overview/Menu.kt
app/src/main/java/com/github/lookupgroup27/lookup/util/NetworkUtils.kt
app/src/main/java/com/github/lookupgroup27/lookup/util/ToastHelper.kt

This PR implements offline mode functionality for the application by restricting access to specific features when the user is not connected to the internet. It ensures a seamless user experience by blocking unavailable features and providing clear feedback to the user.
During the initial PR, the CI behaved unpredictably due to lingering tests that were deleted but still persisted in the pipeline. Despite attempts to resolve the issue, it was deemed risky to clear caches or manipulate the CI further. To work around this, a new branch was created, and the exact same changes were replicated to bypass the CI's persistent issues. This approach ensures that the changes can be validated without unnecessary risk.
- Restricted access to the Google Map and Calendar features when offline.
- Only the …

Implement offline mode handling

---

app/src/main/java/com/github/lookupgroup27/lookup/model/map/planets/PlanetsRepository.kt

This PR addresses the issue [#314](https://github.com/LookUpGroup27/LookUp/issues/314)
**Changes Made:**
- Fixed Retrieval of RA and DEC: Updated the logic for extracting RA (Right Ascension) and DEC (Declination) values from the JSON response to accommodate variations in the API's format.
- Improved Error Handling: Removed the exception throw when the response is unsuccessful to prevent app crashes during periods of slow or unstable internet connectivity.
**Impact:**
- Prevents crashes caused by unexpected JSON structure in Horizons API responses.
- Enhances app stability and user experience during network issues.

fix: Handle edge case of Horizons API responses
